In [7]:
%%sh
conda install -c anaconda scikit-learn 

Solving environment: ...working... done

## Package Plan ##

  environment location: /anaconda3/envs/jupyterlab

  added / updated specs: 
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2018.03.07 |                0         124 KB  anaconda
    scikit-learn-0.20.1        |   py37h4f467ca_0         5.2 MB  anaconda
    mkl-2019.1                 |              144       154.4 MB  anaconda
    openssl-1.1.1              |       h1de35cc_0         4.6 MB  anaconda
    mkl_fft-1.0.6              |   py37hb8a8100_0         137 KB  anaconda
    numpy-1.15.4               |   py37h6a91979_0          35 KB  anaconda
    python-3.7.1               |       haf84260_3        21.1 MB  anaconda
    certifi-2018.10.15         |           py37_0         138 KB  anaconda
    libgfortran-3.0.1          |       h93005f0_2         495 KB  anaconda
    mkl_random-1.0.1 



==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.5.12

Please update conda by running

    $ conda update -n base -c defaults conda


ca-certificates-2018 | 124 KB    | ########## | 100% 
scikit-learn-0.20.1  | 5.2 MB    | ########## | 100% 
mkl-2019.1           | 154.4 MB  | ########## | 100% 
openssl-1.1.1        | 4.6 MB    | ########## | 100% 
mkl_fft-1.0.6        | 137 KB    | ########## | 100% 
numpy-1.15.4         | 35 KB     | ########## | 100% 
python-3.7.1         | 21.1 MB   | ########## | 100% 
certifi-2018.10.15   | 138 KB    | ########## | 100% 
libgfortran-3.0.1    | 495 KB    | ########## | 100% 
mkl_random-1.0.1     | 335 KB    | ########## | 100% 
numpy-base-1.15.4    | 4.1 MB    | ########## | 100% 
libcxxabi-4.0.1      | 458 KB    | ########## | 100% 
scipy-1.1.0          | 15.3 MB   | ########## | 100% 
blas-1.0             | 5 KB      | ########## | 100% 
libcxx-4.0.1         | 1.2 MB    | ########## | 100% 
intel-o

In [8]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC(gamma='scale')
clf.fit(X, y)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
clf.predict([[2., 2.]])

array([1])

In [15]:
print(r)

[1]


In [16]:
r = clf.predict([[0., 1.]])

In [17]:
print(r)

[1]


In [22]:
clf.predict([[0.5, 0.4]])

array([0])

In [19]:
print (r)

[0]


In [6]:
import numpy
numpy.linspace(0.0, 1.0, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])